### get all actors   ###
GET http://localhost:8090/actors
Accept: application/json

### GET actos por paginacion ###
GET http://localhost:8090/actors?page=2&pageSize=10
Accept: application/json

###  get actor by id ###
GET http://localhost:8090/actors/20
Accept: application/json

### post actor  ###
POST http://localhost:8090/actors
Content-Type: application/json

{
    "first_name": "juanita",
    "last_name": "peres"
}

### Put actor ###

PUT http://localhost:8090/actors/201
Content-Type: application/json

{
    "first_name": "Juanita",
    "last_name": "Perez"
}

### Delete actor ###
DELETE http://localhost:8090/actors/207
Accept: application/json

### fin ###